version: "3.7"
services:
  vpncontainer:
    image: ducmthai/nord:latest
    build:
      context: ./
    container_name: vpncontainer
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./vpn.config:/vpn/vpn.config:ro
      - nord_profiles:/vpn/config/
      - ./vpnpasswd:/vpn/vpnpasswd:ro
    env_file: .env
    networks:
      - vpncontainer
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0    
      - net.ipv4.tcp_keepalive_intvl=45
      - net.ipv4.tcp_keepalive_probes=15
      - net.ipv4.tcp_keepalive_time=300    
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

networks:
  vpncontainer:
    name: vpncontainer

volumes:
  nord_profiles:
    name: nord_profiles
