#!/usr/bin/with-contenv sh
set -e -u -o pipefail

if [ ${PROXY_MODE} != "http" ]; then
  echo "Privoxy is disabled!"
  sleep infinity
fi


if [ ! -r ${CONTAINER_CFG} ]; then
  echo "Could not load config file from ${CONTAINER_CFG}. Please check your volume config" 1>&2
  exit 1
fi

source ${CONTAINER_CFG}

while ! $(ip link | grep -q tun0); do sleep 1; done
echo "OpenVPN is running"

if [ -z "${PROXY_PORT}" ]; then
  echo "No port is set, exiting"
  exit 1
fi

echo "Starting privoxy on port ${PROXY_PORT}"
privoxy --no-daemon /etc/privoxy/config 