#!/bin/sh
sleep 10

gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

if [ -z "${PROXY_PORT}" ]; then
  echo "No port is set, exiting"
  exit 1
fi

# Get remote target for kill switch whitelist
export CONFIG_PATH=/vpn/ovpn/config/ovpn_${PROTOCOL}/${REGION}.nordvpn.com.${PROTOCOL}.ovpn
REMOTE_TARGET=$(grep 'remote ' ${CONFIG_PATH} | awk '/remote/ {print $2}')

echo "Enabling kill switch"
# Disable ipv6
sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw

# Get docker network subnet cidr on eth0
subnet_cidr=$(ip -o -f inet addr show | grep eth0 |  awk '/scope global/ {print $4}')
ufw default deny incoming
ufw default deny outgoing
ufw allow in on tun0
ufw allow out on tun0
ufw allow in on eth0 to any port ${PROXY_PORT} from ${LOCAL_NETWORK}
ufw allow in on eth0 to any port ${PROXY_PORT} from ${subnet_cidr}
ufw allow out on eth0 to ${LOCAL_NETWORK}
ufw allow out on eth0 to ${subnet_cidr}
ufw allow out on eth0 to ${REMOTE_TARGET}
ufw enable
ufw status

echo "Starting brook proxy socks5 on port ${PROXY_PORT}"

# start
brook socks5 -l :${PROXY_PORT} -i 0.0.0.0 &> /dev/null
