#!/bin/sh
if [ ${NORD_PROFILES_UPDATE} == "no" ]; then
  exit 0
fi

curl -sSL -N https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -o /vpn/config/ovpn.zip &&
  unzip -o /vpn/config/ovpn.zip -d /vpn/config/ &&
  rm /vpn/config/ovpn.zip
