#!/usr/bin/with-contenv sh

source ${CONTAINER_CFG}

if [ -z "${PROXY_MODE}" ]; then
  echo "No PROXY_MODE is set, exiting"
  exit 1
fi

if [ -z "${USERNAME}" ]; then
  echo "No username is set, exiting"
  exit 1
fi

if [ -z "${PASSWORD}" ]; then
  echo "No password is set, exiting"
  exit 1
fi

echo "Setting username and password"
echo "$USERNAME" >/vpn/auth.conf
echo "$PASSWORD" >>/vpn/auth.conf
chmod 400 /vpn/auth.conf

echo -e "/vpn/auth.conf" >/var/run/s6/container_environment/AUTH_CFG
echo -e "/var/run/openvpn.pid" >/var/run/s6/container_environment/OVPN_PID

[[ ! -f "/vpn/config/updated" ]] &&
  mkdir -p /vpn/config &&
  wget -nv https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -O /vpn/config/ovpn.zip &&
  unzip -o /vpn/config/ovpn.zip -d /vpn/config/ &&
  rm /vpn/config/ovpn.zip &&
  touch /vpn/config/updated
chmod +x /etc/periodic/monthly/update-nordvpn-profiles

# Add a route for local network to use the proxy
gw=$(ip route | awk '/default/ {print $3}')
ip route add ${LOCAL_NETWORK} via $gw dev eth0

OVPN_CONFIG_PATH="/vpn/config/ovpn_${PROTOCOL}/${REGION}.nordvpn.com.${PROTOCOL}.ovpn"
echo -e "/vpn/config/ovpn_${PROTOCOL}/${REGION}.nordvpn.com.${PROTOCOL}.ovpn" >/var/run/s6/container_environment/OVPN_CONFIG_PATH

if [ ! -f ${OVPN_CONFIG_PATH} ]; then
  echo "${OVPN_CONFIG_PATH} is not exist. Exiting"
  exit 1
fi

if [ ! -f /etc/3proxy/updated ]; then
  if [ -n "${HC_PORT}" ]; then 
    echo "Healthcheck port HTTP ${HC_PORT}"
    echo "proxy -p${HC_PORT} -Detun0" >>/etc/3proxy/3proxy.cfg
  fi
  if [ ${PROXY_MODE} = "http" ]; then
    echo "HTTP is enabled!"
    echo "proxy -p${PROXY_PORT} -Detun0" >>/etc/3proxy/3proxy.cfg
  else
    echo "SOCKS5 is enabled!"
    echo "socks -p${PROXY_PORT} -Detun0" >>/etc/3proxy/3proxy.cfg
  fi
  touch /etc/3proxy/updated
fi
